# Используем Debian-based образ, а не Alpine
FROM node:20-bullseye

# Рабочая директория
WORKDIR /app

# Копируем манифесты зависимостей
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install --legacy-peer-deps

# Копируем остальные файлы проекта
COPY . .

# Открываем порт для Vite
EXPOSE 3000

# Запуск dev-сервера с доступом извне
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
