FROM node:20-alpine

WORKDIR /app

# копируем package.json и lock-файл
COPY package*.json ./

# устанавливаем зависимости
RUN npm install --legacy-peer-deps

# копируем весь код
COPY . .

EXPOSE 3000

# запускаем dev-сервер Vite
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
