FROM node:18

WORKDIR /app

COPY package*.json ./
RUN npm install

# Устанавливаем nodemon глобально
RUN npm install -g nodemon

COPY . .

EXPOSE 5000

# Вместо "npm start" запускаем nodemon
CMD ["nodemon", "index.js"]
